FROM php:8.2-apache

RUN apt-get update && apt-get install -y libpq-dev     && docker-php-ext-install pdo pdo_pgsql     && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
CMD ["apache2-foreground"]
